### ISSUE TITLE
师傅请问一下burp6.0按照你这样设置修改生成不能运行

### ISSUE THREAD

**Issue by MaxSecurity** [jaredlew/BurpSuite-jar2app-mac#1]
请问什么情况？

**Comment by jaredlew** [comment]
你可以先尝试用命令行运行一下，然后再排查app转换的问题

**Comment by MaxSecurity** [comment]
> 你可以先尝试用控制台运行一下，然后再排查app转换的问题

命令行java -noverify -javaagent:BurpSuiteLoader.jar -jar -Xmx2048M burpsuite_pro_v2020.6.jar
修改后的命令
jar2app -i icon.icns _pro_v2020.6.jar -j "-noverify -javaagent:/\$APP_ROOT/Contents/Java/BurpSuiteLoader.jar" -o -n "Burp Suite Professional" Burp\ Suite\ Professional

这样搞的

**Comment by jaredlew** [comment]
如果java -noverify -javaagent:BurpSuiteLoader.jar -jar -Xmx2048M burpsuite_pro_v2020.6.jar可以启动，那就把loader复制到*.app/Contents/Java/BurpSuiteLoader.jar，然后到app的目录下面执行open *.app，看一下报错信息。

**Comment by MaxSecurity** [comment]
> 如果java -noverify -javaagent：BurpSuiteLoader.jar -jar -Xmx2048M burpsuite_pro_v2020.6.jar可以启动，那就把loader复制到* .app / Contents / Java / BurpSuiteLoader.jar，然后到应用程序的目录下面执行打开*。 app，看一下报错信息。

并没有报错 打包的app文件一直在跳动然后消失

**Comment by MaxSecurity** [comment]
> 如果java -noverify -javaagent：BurpSuiteLoader.jar -jar -Xmx2048M burpsuite_pro_v2020.6.jar可以启动，那就把loader复制到* .app / Contents / Java / BurpSuiteLoader.jar，然后到应用程序的目录下面执行打开*。 app，看一下报错信息。

并没有报错 打包的app文件一直在跳动然后消失

**Comment by jaredlew** [comment]
可以看看控制台有没有错误信息，一点信息没有没办法排查故障

**Comment by MaxSecurity** [comment]
> 可以看看控制台有没有错误信息，一点信息没有没办法排查故障

控制台也没有任何报错我目前也很懵逼。。。

**Comment by MaxSecurity** [comment]
> 可以看看控制台有没有错误信息，一点信息没有没办法排查故障

这是运行后的生成的信息
burpsuite_pro_v2020.6  jar2app -i icon.icns burpsuite.jar -j "-noverify -javaagent:/\$APP_ROOT/Contents/Java/BurpSuiteLoader.jar" -o -n "Burp Suite Professional" Burp\ Suite\ Professional
jar2app 1.0.1, João Ricardo Lourenço, 2015-2017 <jorl17.8@gmail.com>.
Github page: https://github.com/Jorl17/jar2app/
Packing burpsuite.jar into /Users/xxx/Desktop/BURP/burpsuite_pro_v2020.6/Burp Suite Professional.app
CFBundleIconFile: icon.icns
CFBundleIdentifier: com.jar2app.example.Burp Suite Professional
CFBundleDisplayName: Burp Suite Professional
CFBundleName: Burp Suite Professional
CFBundleShortVersionString: 1.0.1
CFBundleSignature: ????
CFBundleVersion: 1.0.1
Retina support enabled.
macOS menubar support enabled (might not always work).
---
JVMOptions: -noverify -javaagent:/$APP_ROOT/Contents/Java/BurpSuiteLoader.jar
JVMMainClassName: burp.StartBurp
Executable Name (CFBundleExecutable): JavaAppLauncher
JAR Working directory: $APP_ROOT/Contents

burpsuite.jar packaged to /Users/XXX/Desktop/BURP/burpsuite_pro_v2020.6/Burp Suite Professional.app.
●﹏●  burpsuite_pro_v2020.6

**Comment by jaredlew** [comment]
> > 可以看看控制台有没有错误信息，一点信息没有没办法排查故障
> 
> ## 这是运行后的生成的信息
> burpsuite_pro_v2020.6 jar2app -i icon.icns burpsuite.jar -j "-noverify -javaagent:/$APP_ROOT/Contents/Java/BurpSuiteLoader.jar" -o -n "Burp Suite Professional" Burp\ Suite\ Professional
> jar2app 1.0.1, João Ricardo Lourenço, 2015-2017 [jorl17.8@gmail.com](mailto:jorl17.8@gmail.com).
> Github page: https://github.com/Jorl17/jar2app/
> Packing burpsuite.jar into /Users/xxx/Desktop/BURP/burpsuite_pro_v2020.6/Burp Suite Professional.app
> CFBundleIconFile: icon.icns
> CFBundleIdentifier: com.jar2app.example.Burp Suite Professional
> CFBundleDisplayName: Burp Suite Professional
> CFBundleName: Burp Suite Professional
> CFBundleShortVersionString: 1.0.1
> CFBundleSignature: ????
> CFBundleVersion: 1.0.1
> Retina support enabled.
> macOS menubar support enabled (might not always work).
> JVMOptions: -noverify -javaagent:/$APP_ROOT/Contents/Java/BurpSuiteLoader.jar
> JVMMainClassName: burp.StartBurp
> Executable Name (CFBundleExecutable): JavaAppLauncher
> JAR Working directory: $APP_ROOT/Contents
> 
> burpsuite.jar packaged to /Users/XXX/Desktop/BURP/burpsuite_pro_v2020.6/Burp Suite Professional.app.
> ●﹏● burpsuite_pro_v2020.6

这里没看到什么问题，建议你按照我写的命令进行封装，这里面的参数我并不是很懂，看起来你的封装命令是参考别人的写的，你对比一下在`-Xbootclasspath/p:/`那里的部分，这个是破解的loader，另外记得封装完以后把你的loader复制到app的content里，复制的位置是你封装的时候指定的目录，然后启动用terminal定位到封装好的app里面，一般位置为`Contents/MacOS`使用命令./JavaAppLauncher 执行里面的启动程序，看看有没有报错，你给我的信息没法判断是那里出问题了。

**Comment by MaxSecurity** [comment]
111
